### ISSUE TITLE
Download issues

### ISSUE THREAD

**Issue by KosmoGamer** [cabalex/fnf-song-converter#16]
I uploaded the JSON file to the converter and it doesn't show the download button for some reason. Maybe there's a problem with the latest update. Note: Only specific songs work like sometimes the matt songs, Kapi, and Miku. But Aflac won't work.

**Comment by KosmoGamer** [comment]
![Screenshot 2022-03-26 10 35 57 AM](https://user-images.githubusercontent.com/100534215/160244274-18f1824f-0675-4e44-a550-f2d93aa8cf36.png)

Oof

**Comment by KosmoGamer** [comment]
That's the song lol.

**Comment by KosmoGamer** [comment]
Also trying to do the end from the aflac mod but ends up like trance.
(Am doing a remastered version)

**Comment by cabalex** [comment]
Open the console after trying to convert (CTRL + SHIFT + J). Are there any errors, and if so, can you put them here?

If you could send the chart JSON files that wouldn't convert as well, that would be super helpful.

**Comment by KosmoGamer** [comment]
It works now.
I'll let you know if there are any other issues with the JSON or the Chart. (I just happen to use the converter almost everyday so I'll be free to let you know.)
Note: I tried the file again and for some reason it works now. I don't think something is wrong with the file, but probably the converter. 
(It's a possibility but it's unlikely)

**Comment by KosmoGamer** [comment]
Sorry if it doesn't make much sense. I'm a beginner anyways.

**Comment by KosmoGamer** [comment]
Can't place the JSON to github comments anyways

**Comment by cabalex** [comment]
If it works now, I'll close the issue-- let me know if you have any further problems.
