### ISSUE TITLE
Have momdad Characters sing together?

### ISSUE THREAD

**Issue by ILikeTrains909** [cabalex/fnf-song-converter#17]
I have two separate things. I am planning to recreate the Black's Betrayal mod, and for songs such as Betrayal and Double Trouble, 1: Is there a way to have momdad Characters sing together? And 2: Is there a way to swap between 2 different BFs or have 2 on one screen, while having them switch between each other? With a remixed engine, I tried copying BF sprite, which works, but I don't know how to make them sing together or separately at different times. If you can solve these not-really-issues, it would be very helpful. Thanks!

**Comment by cabalex** [comment]
1. Unfortunately, the momdad triggers don't allow for both characters to be singing at once- the separate list merely provides timings for the two to switch places. You'll have to find an engine that allows for this or modify the engine yourself.
2. Again, the engine only supports one BF (the "Player"), so you'd have to modify it to allow for more than one player character. You could potentially use some of the momdad code to help with this regard, though as you mention, it doesn't support both characters singing together.

Sorry I couldn't really solve your issue-- it's not really something the converter has any part in.
