### ISSUE TITLE
Change costume

### ISSUE THREAD

**Issue by Samfitzgamer2022** [cabalex/fnf-song-converter#18]
How do I change the costume to go further? etc, longer idle animation.
Sorry if I couldn't explain it properly

**Comment by alex343xd** [comment]
![image](https://user-images.githubusercontent.com/65650545/184980876-8f42eaaf-5958-4254-8c74-85e8d60dac04.png)
change the "repeat until costume number = 4" thing to the amount of sprites your idle animation has. Im pretty sure the singing animations are self configured if the idle animation is first

**Comment by cabalex** [comment]
The above solution fixes this issue, so I'll close it for now.
