### ISSUE TITLE
Duets are bugged out

### ISSUE THREAD

**Issue by ExtemTheHedgepog** [cabalex/fnf-song-converter#3]
I made a custom chart for a song I made and converted it to the scratch version for use with my custom character (who is also me.) Things worked out just fine until the part where they sang together with the same notes. Instead of singing together, Boyfriend sang some parts and I sang others. Is there a way to fix this?

**Comment by cabalex** [comment]
Strange... I'm not really sure if I can create the issue you described on my own. Do you mind sending me the JSON song beatmap so I can troubleshoot it?

**Comment by ExtemTheHedgepog** [comment]
I edited the beginning of Senpai to show off the glitch:
`{"song":{"sectionLengths":[],"player1":"bf-pixel","player2":"senpai","notes":[{"typeOfSection":0,"sectionNotes":[[0,3,0],[416.666666666667,3,0],[625,0,0],[833.333333333333,2,208.333333333333],[1250,1,208.333333333333]],"lengthInSteps":16,"altAnim":false,"bpm":150,"changeBPM":false,"mustHitSection":false},{"typeOfSection":0,"sectionNotes":[[1666.66666666667,3,208.333333333333],[2187.5,1,833.333333333333]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":false},{"typeOfSection":0,"sectionNotes":[[3333.33333333333,3,0],[3750,3,0],[3958.33333333333,0,0],[4166.66666666667,2,208.333333333333],[4583.33333333333,1,208.333333333333]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":true},{"typeOfSection":0,"sectionNotes":[[5000,3,208.333333333333],[5416.66666666667,2,0],[5625,3,208.333333333333],[6041.66666666667,2,0],[6250,3,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":true},{"typeOfSection":0,"sectionNotes":[[6666.66666666667,1,0],[7083.33333333333,1,0],[7500,2,0],[7916.66666666667,1,0],[6666.66666666667,5,0],[7083.33333333333,5,0],[7500,6,0],[7916.66666666667,5,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":false},{"typeOfSection":0,"sectionNotes":[[8333.33333333333,3,312.5],[8333.33333333333,7,312.5],[8750,1,0],[8958.33333333333,4,312.5],[8958.33333333333,0,312.5],[9375,5,0],[9375,1,0],[8750,5,0],[9583.33333333333,7,0],[9583.33333333333,3,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":true},{"typeOfSection":0,"sectionNotes":[[10000,3,0],[10416.6666666667,1,0],[10416.6666666667,5,0],[10833.3333333333,0,0],[11041.6666666667,4,0],[11250,5,208.333333333333],[11250,1,208.333333333333],[10000,7,0],[10833.3333333333,4,0],[11041.6666666667,0,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":false},{"typeOfSection":0,"sectionNotes":[[11666.6666666667,3,0],[12083.3333333333,1,0],[12500,2,0],[13125,2,0],[12083.3333333333,5,0],[12500,6,0],[12916.6666666667,7,0],[13125,6,0],[11666.6666666667,7,0],[12708.3333333333,0,0],[12708.3333333333,4,0],[12916.6666666667,3,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":true},{"typeOfSection":0,"sectionNotes":[[13750,2,312.5],[14166.6666666667,1,312.5],[14791.6666666667,3,416.666666666667]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":false},{"typeOfSection":0,"sectionNotes":[[15729.1666666667,2,0],[16250,1,208.333333333333],[15625,0,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":false},{"typeOfSection":0,"sectionNotes":[[16666.6666666667,3,312.5],[17083.3333333333,1,0],[17291.6666666667,0,625]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":false},{"typeOfSection":0,"sectionNotes":[[18333.3333333333,1,416.666666666667],[18958.3333333333,0,312.5],[19479.1666666667,3,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":false},{"typeOfSection":0,"sectionNotes":[[20416.6666666667,2,312.5],[20833.3333333333,1,312.5],[21458.3333333333,3,416.666666666667],[20000,5,312.5]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":true},{"typeOfSection":0,"sectionNotes":[[22395.8333333333,2,0],[22333.3333333333,0,0],[22916.6666666667,1,208.333333333333]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":true},{"typeOfSection":0,"sectionNotes":[[23333.3333333333,3,312.5],[23750,1,0],[23958.3333333333,0,625]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":true},{"typeOfSection":0,"sectionNotes":[[25000,1,416.666666666667],[25625,0,312.5],[26145.8333333333,3,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":true},{"typeOfSection":0,"sectionNotes":[[26666.6666666667,5,625],[27395.8333333333,7,729.166666666667],[26666.6666666667,2,0],[27083.3333333333,1,0],[27500,2,0],[27708.3333333333,3,0],[27916.6666666667,0,0],[28125,3,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":false},{"typeOfSection":0,"sectionNotes":[[28333.3333333333,0,520.833333333333],[28333.3333333333,6,0],[28750,7,0],[28958.3333333333,7,0],[29166.6666666667,4,0],[29375,4,0],[29166.6666666667,3,520.833333333333],[29583.3333333333,5,208.333333333333]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":true},{"typeOfSection":0,"sectionNotes":[[30000,6,625],[30833.3333333333,7,625],[30000,3,0],[30416.6666666667,0,0],[30625,1,625],[31458.3333333333,3,416.666666666667],[30000,6,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":false},{"typeOfSection":0,"sectionNotes":[[31666.6666666667,0,625],[32500,1,625],[32083.3333333333,6,0],[32291.6666666667,4,0],[32708.3333333333,5,0],[32916.6666666667,7,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":true},{"typeOfSection":0,"sectionNotes":[[33333.3333333333,0,0],[34166.6666666667,2,0],[34375,0,0],[34583.3333333333,3,0],[34791.6666666667,0,0],[33750,0,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":true},{"typeOfSection":0,"sectionNotes":[[35000,3,208.333333333333],[35416.6666666667,1,208.333333333333],[35833.3333333333,2,0],[36041.6666666667,3,0],[36250,0,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":true},{"typeOfSection":0,"sectionNotes":[[36666.6666666667,3,0],[37083.3333333333,1,0],[37291.6666666667,0,520.833333333333],[38125,3,312.5]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":true},{"typeOfSection":0,"sectionNotes":[[38750,1,0],[38958.3333333333,3,0],[39375,0,0],[39583.3333333333,1,208.333333333333]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":true},{"typeOfSection":0,"sectionNotes":[[40000,6,312.5],[40000,2,312.5],[40416.6666666667,0,0],[40833.3333333333,3,312.5],[41250,1,0],[41354.1666666667,0,520.833333333333],[40520.8333333333,1,0],[40625,0,0],[40729.1666666667,1,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":false},{"typeOfSection":0,"sectionNotes":[[42291.6666666667,1,312.5],[42708.3333333333,3,312.5],[43125,0,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":false},{"typeOfSection":0,"sectionNotes":[[43333.3333333333,3,312.5],[43750,0,0],[43958.3333333333,2,312.5],[44375,0,0],[44583.3333333333,2,0],[44791.6666666667,0,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":false},{"typeOfSection":0,"sectionNotes":[[45000,3,0],[45416.6666666667,3,0],[45625,1,0],[45833.3333333333,3,0],[46041.6666666667,2,0],[46250,3,0],[46458.3333333333,0,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":false},{"typeOfSection":0,"sectionNotes":[[46666.6666666667,2,312.5],[47083.3333333333,0,0],[47187.5,1,0],[47291.6666666667,0,0],[47395.8333333333,1,0],[47500,3,312.5],[47916.6666666667,1,0],[48020.8333333333,0,520.833333333333]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":true},{"typeOfSection":0,"sectionNotes":[[48958.3333333333,1,312.5],[49375,3,312.5],[49791.6666666667,0,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":true},{"typeOfSection":0,"sectionNotes":[[50000,3,312.5],[50416.6666666667,0,0],[50625,2,312.5],[51041.6666666667,0,0],[51250,2,0],[51458.3333333333,0,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":true},{"typeOfSection":0,"sectionNotes":[[51666.6666666667,3,0],[52083.3333333333,3,0],[52291.6666666667,1,0],[52500,3,0],[52916.6666666667,3,0],[53125,0,0],[52708.3333333333,2,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":true},{"typeOfSection":0,"sectionNotes":[[53333.3333333333,3,0],[53750,3,0],[53958.3333333333,0,0],[54166.6666666667,2,208.333333333333],[54583.3333333333,1,208.333333333333]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":false},{"typeOfSection":0,"sectionNotes":[[55000,3,208.333333333333],[55520.8333333333,1,833.333333333333]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":false},{"typeOfSection":0,"sectionNotes":[[56666.6666666667,3,0],[57083.3333333333,3,0],[57291.6666666667,0,0],[57500,2,208.333333333333],[57916.6666666667,1,208.333333333333]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":true},{"typeOfSection":0,"sectionNotes":[[58333.3333333333,3,208.333333333333],[58750,2,0],[58958.3333333333,3,208.333333333333],[59375,2,0],[59583.3333333333,3,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":true},{"typeOfSection":0,"sectionNotes":[[60000,1,0],[60416.6666666667,1,0],[60833.3333333333,2,0],[61250,1,0],[60000,5,0],[60416.6666666667,5,0],[60833.3333333333,6,0],[61250,5,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":true},{"typeOfSection":0,"sectionNotes":[[61666.6666666667,3,312.5],[61666.6666666667,7,312.5],[62083.3333333333,1,0],[62291.6666666667,4,312.5],[62291.6666666667,0,312.5],[62708.3333333333,5,0],[62708.3333333333,1,0],[62083.3333333333,5,0],[62916.6666666667,7,0],[62916.6666666667,0,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":true},{"typeOfSection":0,"sectionNotes":[[63333.3333333333,4,0],[63333.3333333333,3,0],[63750,1,0],[63750,5,0],[64166.6666666667,7,0],[64166.6666666667,0,0],[64375,4,0],[64375,3,0],[64583.3333333333,5,208.333333333333],[64583.3333333333,1,208.333333333333]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":false},{"typeOfSection":0,"sectionNotes":[[65000,3,0],[65416.6666666667,1,0],[65833.3333333333,2,0],[66041.6666666667,3,0],[66250,0,0],[66458.3333333333,2,0],[65000,4,0],[65416.6666666667,5,0],[65833.3333333333,6,0],[66041.6666666667,4,0],[66250,7,0],[66458.3333333333,6,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":true},{"typeOfSection":0,"sectionNotes":[[66666.6666666667,1,0],[66875,3,0],[67083.3333333333,0,0],[67500,1,0],[67708.3333333333,3,0],[67916.6666666667,0,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":false},{"typeOfSection":0,"sectionNotes":[[68333.3333333333,1,0],[68541.6666666667,3,0],[68750,0,0],[69166.6666666667,2,0],[69375,3,0],[69583.3333333333,0,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":false},{"typeOfSection":0,"sectionNotes":[[70000,1,0],[70208.3333333333,3,0],[70416.6666666667,0,0],[70833.3333333333,1,0],[71041.6666666667,3,0],[71250,0,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":true},{"typeOfSection":0,"sectionNotes":[[71666.6666666667,1,0],[71875,3,0],[72083.3333333333,0,0],[72500,2,0],[72708.3333333333,3,0],[72916.6666666667,0,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":true},{"typeOfSection":0,"sectionNotes":[[73333.3333333333,1,0],[73541.6666666667,3,0],[73750,0,0],[74166.6666666667,1,0],[74375,3,0],[74583.3333333333,0,0],[74791.6666666667,3,0],[73958.3333333333,3,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":false},{"typeOfSection":0,"sectionNotes":[[75000,1,0],[75208.3333333333,3,0],[75416.6666666667,0,0],[75625,3,0],[75833.3333333333,2,0],[76041.6666666667,3,0],[76250,0,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":false},{"typeOfSection":0,"sectionNotes":[[76875,3,0],[77083.3333333333,0,0],[77291.6666666667,3,0],[77500,1,0],[77708.3333333333,3,0],[77916.6666666667,0,0],[78125,3,0],[76666.6666666667,1,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":true},{"typeOfSection":0,"sectionNotes":[[78333.3333333333,1,0],[78541.6666666667,3,0],[78750,0,0],[78958.3333333333,3,0],[79166.6666666667,2,0],[79375,3,0],[79583.3333333333,0,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":true},{"typeOfSection":0,"sectionNotes":[[80000,2,312.5],[80416.6666666667,0,0],[80520.8333333333,1,0],[80625,0,0],[80729.1666666667,1,0],[80833.3333333333,3,312.5],[81250,1,0],[81354.1666666667,0,520.833333333333]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":false},{"typeOfSection":0,"sectionNotes":[[82291.6666666667,1,312.5],[82708.3333333333,3,312.5],[83125,0,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":false},{"typeOfSection":0,"sectionNotes":[[83333.3333333333,3,312.5],[83750,0,0],[83958.3333333333,2,312.5],[84375,0,0],[84583.3333333333,2,0],[84791.6666666667,0,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":false},{"typeOfSection":0,"sectionNotes":[[85000,3,0],[85208.3333333333,1,0],[85312.5,0,0],[85416.6666666667,3,0],[85625,1,0],[85833.3333333333,3,0],[86041.6666666667,2,0],[86250,3,0],[86458.3333333333,0,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":false},{"typeOfSection":0,"sectionNotes":[[86666.6666666667,2,312.5],[87083.3333333333,0,0],[87187.5,1,0],[87291.6666666667,0,0],[87395.8333333333,1,0],[87500,3,312.5],[87916.6666666667,1,0],[88020.8333333333,0,520.833333333333]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":true},{"typeOfSection":0,"sectionNotes":[[88958.3333333333,1,312.5],[89375,3,312.5],[89791.6666666667,0,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":true},{"typeOfSection":0,"sectionNotes":[[90000,3,312.5],[90416.6666666667,0,0],[90625,2,312.5],[91041.6666666667,0,0],[91250,2,0],[91458.3333333333,0,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":true},{"typeOfSection":0,"sectionNotes":[[91666.6666666667,3,0],[92083.3333333333,3,0],[92291.6666666667,1,0],[92500,3,0],[92708.3333333333,2,0],[92916.6666666667,3,0],[93125,0,0]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":true},{"typeOfSection":0,"sectionNotes":[[93333.3333333333,0,729.166666666667]],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":true},{"typeOfSection":0,"sectionNotes":[],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":false},{"typeOfSection":0,"sectionNotes":[],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":false},{"typeOfSection":0,"sectionNotes":[],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":false},{"typeOfSection":0,"sectionNotes":[],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":false},{"typeOfSection":0,"sectionNotes":[],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":false},{"typeOfSection":0,"sectionNotes":[],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":true},{"typeOfSection":0,"sectionNotes":[],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":false},{"typeOfSection":0,"sectionNotes":[],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":false},{"typeOfSection":0,"sectionNotes":[],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":false},{"typeOfSection":0,"sectionNotes":[],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":false},{"typeOfSection":0,"sectionNotes":[],"lengthInSteps":16,"altAnim":false,"bpm":144,"changeBPM":false,"mustHitSection":false},{"lengthInSteps":16,"altAnim":false,"typeOfSection":0,"sectionNotes":[],"bpm":144,"changeBPM":false,"mustHitSection":true}],"song":"Senpai","validScore":true,"sections":0,"needsVoices":true,"speed":1.2,"bpm":144}}`
Converted, it looks like this:
`?0000000_3_0
#0-0
?0000416.6667_3_0
?0000625_0_0
?0000833.3333_2_208.333333333333
?0001250_1_208.333333333333
#0-1666.6666666666667
?0001666.6667_3_208.333333333333
?0002187.5000_1_833.333333333333
?0003333.3333_7_0
#1-3333.3333333333335
?0003750_7_0
?0003958.3333_4_0
?0004166.6667_6_208.333333333333
?0004583.3333_5_208.333333333333
?0005000_7_208.333333333333
#1-5000
?0005416.6667_6_0
?0005625_7_208.333333333333
?0006041.6667_6_0
?0006250_7_0
#0-6666.666666666667
?0006666.6667_5_0
?0007083.3333_5_0
?0007500_6_0
?0007916.6667_5_0
?0008333.3333_3_312.5
#1-8333.333333333334
?0008750_1_0
?0008958.3333_4_312.5
?0009375_5_0
?0009583.3333_7_0
?0010000_7_0
#0-10000
?0010416.6667_5_0
?0010833.3333_4_0
?0011041.6667_0_0
?0011250_1_208.333333333333
#1-11666.666666666666
?0011666.6667_3_0
?0012083.3333_1_0
?0012500_2_0
?0012708.3333_0_0
?0012916.6667_7_0
?0013125_2_0
#0-13333.333333333332
?0013750_2_312.5
?0014166.6667_1_312.5
?0014791.6667_3_416.666666666667
#0-14999.999999999998
?0015625_0_0
?0015729.1667_2_0
?0016250_1_208.333333333333
#0-16666.666666666664
?0016666.6667_3_312.5
?0017083.3333_1_0
?0017291.6667_0_625
?0018333.3333_1_416.666666666667
#0-18333.333333333332
?0018958.3333_0_312.5
?0019479.1667_3_0
?0020000_1_312.5
#1-20000
?0020416.6667_6_312.5
?0020833.3333_5_312.5
?0021458.3333_7_416.666666666667
#1-21666.666666666668
?0022333.3333_4_0
?0022395.8333_6_0
?0022916.6667_5_208.333333333333
?0023333.3333_7_312.5
#1-23333.333333333336
?0023750_5_0
?0023958.3333_4_625
?0025000_5_416.666666666667
#1-25000.000000000004
?0025625_4_312.5
?0026145.8333_7_0
#0-26666.66666666667
?0026666.6667_2_0
?0027083.3333_1_0
?0027395.8333_7_729.166666666667
?0027500_2_0
?0027708.3333_3_0
?0027916.6667_0_0
?0028125_3_0
?0028333.3333_2_0
#1-28333.33333333334
?0028750_3_0
?0028958.3333_3_0
?0029166.6667_7_520.833333333333
?0029375_0_0
?0029583.3333_1_208.333333333333
?0030000_6_0
#0-30000.000000000007
?0030416.6667_0_0
?0030625_1_625
?0030833.3333_7_625
?0031458.3333_3_416.666666666667
#1-31666.666666666675
?0031666.6667_4_625
?0032083.3333_2_0
?0032291.6667_0_0
?0032500_5_625
?0032708.3333_1_0
?0032916.6667_3_0
?0033333.3333_4_0
#1-33333.33333333334
?0033750_4_0
?0034166.6667_6_0
?0034375_4_0
?0034583.3333_7_0
?0034791.6667_4_0
?0035000_7_208.333333333333
#1-35000.00000000001
?0035416.6667_5_208.333333333333
?0035833.3333_6_0
?0036041.6667_7_0
?0036250_4_0
#1-36666.66666666667
?0036666.6667_7_0
?0037083.3333_5_0
?0037291.6667_4_520.833333333333
?0038125_7_312.5
#1-38333.333333333336
?0038750_5_0
?0038958.3333_7_0
?0039375_4_0
?0039583.3333_5_208.333333333333
?0040000_2_312.5
#0-40000
?0040416.6667_0_0
?0040520.8333_1_0
?0040625_0_0
?0040729.1667_1_0
?0040833.3333_3_312.5
?0041250_1_0
?0041354.1667_0_520.833333333333
#0-41666.666666666664
?0042291.6667_1_312.5
?0042708.3333_3_312.5
?0043125_0_0
?0043333.3333_3_312.5
#0-43333.33333333333
?0043750_0_0
?0043958.3333_2_312.5
?0044375_0_0
?0044583.3333_2_0
?0044791.6667_0_0
#0-44999.99999999999
?0045000_3_0
?0045416.6667_3_0
?0045625_1_0
?0045833.3333_3_0
?0046041.6667_2_0
?0046250_3_0
?0046458.3333_0_0
#1-46666.66666666666
?0046666.6667_6_312.5
?0047083.3333_4_0
?0047187.5000_5_0
?0047291.6667_4_0
?0047395.8333_5_0
?0047500_7_312.5
?0047916.6667_5_0
?0048020.8333_4_520.833333333333
#1-48333.33333333332
?0048958.3333_5_312.5
?0049375_7_312.5
?0049791.6667_4_0
#1-49999.999999999985
?0050000_7_312.5
?0050416.6667_4_0
?0050625_6_312.5
?0051041.6667_4_0
?0051250_6_0
?0051458.3333_4_0
#1-51666.66666666665
?0051666.6667_7_0
?0052083.3333_7_0
?0052291.6667_5_0
?0052500_7_0
?0052708.3333_6_0
?0052916.6667_7_0
?0053125_4_0
?0053333.3333_3_0
#0-53333.333333333314
?0053750_3_0
?0053958.3333_0_0
?0054166.6667_2_208.333333333333
?0054583.3333_1_208.333333333333
#0-54999.99999999998
?0055000_3_208.333333333333
?0055520.8333_1_833.333333333333
#1-56666.66666666664
?0056666.6667_7_0
?0057083.3333_7_0
?0057291.6667_4_0
?0057500_6_208.333333333333
?0057916.6667_5_208.333333333333
?0058333.3333_7_208.333333333333
#1-58333.33333333331
?0058750_6_0
?0058958.3333_7_208.333333333333
?0059375_6_0
?0059583.3333_7_0
#1-59999.99999999997
?0060000_1_0
?0060416.6667_1_0
?0060833.3333_2_0
?0061250_1_0
#1-61666.666666666635
?0061666.6667_3_312.5
?0062083.3333_1_0
?0062291.6667_4_312.5
?0062708.3333_5_0
?0062916.6667_4_0
?0063333.3333_3_0
#0-63333.3333333333
?0063750_5_0
?0064166.6667_0_0
?0064375_3_0
?0064583.3333_1_208.333333333333
#1-64999.99999999996
?0065000_0_0
?0065416.6667_1_0
?0065833.3333_2_0
?0066041.6667_0_0
?0066250_3_0
?0066458.3333_2_0
#0-66666.66666666663
?0066666.6667_1_0
?0066875_3_0
?0067083.3333_0_0
?0067500_1_0
?0067708.3333_3_0
?0067916.6667_0_0
?0068333.3333_1_0
#0-68333.3333333333
?0068541.6667_3_0
?0068750_0_0
?0069166.6667_2_0
?0069375_3_0
?0069583.3333_0_0
#1-69999.99999999997
?0070000_5_0
?0070208.3333_7_0
?0070416.6667_4_0
?0070833.3333_5_0
?0071041.6667_7_0
?0071250_4_0
#1-71666.66666666664
?0071666.6667_5_0
?0071875_7_0
?0072083.3333_4_0
?0072500_6_0
?0072708.3333_7_0
?0072916.6667_4_0
?0073333.3333_1_0
#0-73333.33333333331
?0073541.6667_3_0
?0073750_0_0
?0073958.3333_3_0
?0074166.6667_1_0
?0074375_3_0
?0074583.3333_0_0
?0074791.6667_3_0
#0-74999.99999999999
?0075000_1_0
?0075208.3333_3_0
?0075416.6667_0_0
?0075625_3_0
?0075833.3333_2_0
?0076041.6667_3_0
?0076250_0_0
#1-76666.66666666666
?0076666.6667_5_0
?0076875_7_0
?0077083.3333_4_0
?0077291.6667_7_0
?0077500_5_0
?0077708.3333_7_0
?0077916.6667_4_0
?0078125_7_0
?0078333.3333_5_0
#1-78333.33333333333
?0078541.6667_7_0
?0078750_4_0
?0078958.3333_7_0
?0079166.6667_6_0
?0079375_7_0
?0079583.3333_4_0
?0080000_2_312.5
#0-80000
?0080416.6667_0_0
?0080520.8333_1_0
?0080625_0_0
?0080729.1667_1_0
?0080833.3333_3_312.5
?0081250_1_0
?0081354.1667_0_520.833333333333
#0-81666.66666666667
?0082291.6667_1_312.5
?0082708.3333_3_312.5
?0083125_0_0
?0083333.3333_3_312.5
#0-83333.33333333334
?0083750_0_0
?0083958.3333_2_312.5
?0084375_0_0
?0084583.3333_2_0
?0084791.6667_0_0
?0085000_3_0
#0-85000.00000000001
?0085208.3333_1_0
?0085312.5000_0_0
?0085416.6667_3_0
?0085625_1_0
?0085833.3333_3_0
?0086041.6667_2_0
?0086250_3_0
?0086458.3333_0_0
#1-86666.66666666669
?0086666.6667_6_312.5
?0087083.3333_4_0
?0087187.5000_5_0
?0087291.6667_4_0
?0087395.8333_5_0
?0087500_7_312.5
?0087916.6667_5_0
?0088020.8333_4_520.833333333333
#1-88333.33333333336
?0088958.3333_5_312.5
?0089375_7_312.5
?0089791.6667_4_0
?0090000_7_312.5
#1-90000.00000000003
?0090416.6667_4_0
?0090625_6_312.5
?0091041.6667_4_0
?0091250_6_0
?0091458.3333_4_0
#1-91666.6666666667
?0091666.6667_7_0
?0092083.3333_7_0
?0092291.6667_5_0
?0092500_7_0
?0092708.3333_6_0
?0092916.6667_7_0
?0093125_4_0
?0093333.3333_4_729.166666666667
#1-93333.33333333337
#0-95000.00000000004
#0-96666.66666666672
#0-98333.33333333339
#0-100000.00000000006
#0-101666.66666666673
#1-103333.3333333334
#0-105000.00000000007
#0-106666.66666666674
#0-108333.33333333342
#0-110000.00000000009
#0-111666.66666666676
#1-113333.33333333343`
And when I play it in-game, Senpai sings some notes and BF sings others :/

https://user-images.githubusercontent.com/84426237/120112436-d37baf00-c143-11eb-9605-b89cb021338f.mp4

**Comment by cabalex** [comment]
Whoops, fixed with the newest commit! The issue was with the new system (Created with #2) and how it accidentally overwrote the last note when two notes were playing at the same time. Thank you for reporting it!
