### ISSUE TITLE
how to add fire notes to proget

### ISSUE THREAD

**Issue by Tavish-153** [cabalex/fnf-song-converter#4]
I want to add expurgation to  your proget and i just want to add fire nots pls tell me how?

**Comment by cabalex** [comment]
Hi there! Unfortunately, the issues tab here is only for problems related to the converter only (e.g. conversion issues), and I can't really help with adding new features at the moment. You'll be much better off asking someone on the Scratch website who's already dove into extended note shenanigans, like [kris235](https://scratch.mit.edu/projects/547399310).
Sorry for the inconvenience!
