### ISSUE TITLE
the friday night funkin project doesn't work

### ISSUE THREAD

**Issue by gitclonehubgit** [cabalex/fnf-song-converter#5]
it says the server is scratching its head, and turbowarp can't load it either. mind that this is a BUG, not a help report.

**Comment by cabalex** [comment]
Seems working for me on [Scratch](https://scratch.mit.edu/projects/519325355/), [Turbowarp](https://turbowarp.org/519325355/fullscreen?fps=60), and [Forkphorus](https://forkphorus.github.io/#519325355). Maybe it's something on your end? Or maybe Scratch was having some server issues?

**Comment by gitclonehubgit** [comment]
thanks
