### ISSUE TITLE
How do you do this

### ISSUE THREAD

**Issue by ArticFox703** [cabalex/fnf-song-converter#6]
[killer.txt](https://github.com/cabalex/fnf-song-converter/files/7281892/killer.txt)

**Comment by cabalex** [comment]
Make sure to follow the guide at [https://cabalex.github.io/fnf-song-converter/guide/](https://github.com/cabalex/fnf-song-converter/wiki/Making-and-Importing-New-Songs) when creating custom songs; it should tell you all there is to know.

**This is not the place for help requests**, so if you need further help please ask on my [Scratch profile](https://scratch.mit.edu/users/cabalex). 
Thanks!
